model:
  name: google/flan-t5-base
  task: text2text-generation
  max_new_tokens: 256
  trust_remote_code: false

retrieval:
  top_k: 3

chunking:
  size: 1000
  overlap: 100

prompt:
  template: |
    You are a helpful assistant. Use the context below to answer the user's question.

    Context: {context}
    Question: {question}
